"""add championship_link table

Revision ID: 69af855d5519
Revises: a1b2c3d4e5f6
Create Date: 2026-03-31 16:46:17.619386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69af855d5519'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('championship_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('championship_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['championship_id'], ['championship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('championship_link')
    # ### end Alembic commands ###
