"""honor entry links and comuna, creator links, store address

Revision ID: 84ccb1c30994
Revises: 9e9600b917e9
Create Date: 2026-03-28 17:03:10.836895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ccb1c30994'
down_revision = '9e9600b917e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['content_creator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('honor_entry_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['honor_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_creator', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('honor_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comuna', sa.String(length=120), nullable=True))

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('honor_entry', schema=None) as batch_op:
        batch_op.drop_column('comuna')

    with op.batch_alter_table('content_creator', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    op.drop_table('honor_entry_link')
    op.drop_table('creator_link')
    # ### end Alembic commands ###
