"""contact_info notification expired end_date

Revision ID: 9acc7be8c22a
Revises: 25066bc8fc7c
Create Date: 2026-03-26 19:42:16.719869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9acc7be8c22a'
down_revision = '25066bc8fc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contact_info', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('expired', sa.Boolean(), nullable=True))
        batch_op.alter_column('bases_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_column('contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('bases_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('expired')
        batch_op.drop_column('contact_info')
        batch_op.drop_column('end_date')

    op.drop_table('notification')
    # ### end Alembic commands ###
