"""store social links and contacts

Revision ID: 9e9600b917e9
Revises: 7f9902bc89a1
Create Date: 2026-03-28 16:19:36.963905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9600b917e9'
down_revision = '7f9902bc89a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_expired'), ['expired'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_status'), ['status'], unique=False)

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.String(length=500), nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_column('website_url')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_status'))
        batch_op.drop_index(batch_op.f('ix_event_kind'))
        batch_op.drop_index(batch_op.f('ix_event_expired'))
        batch_op.drop_index(batch_op.f('ix_event_date'))

    op.drop_table('store_link')
    op.drop_table('store_contact')
    # ### end Alembic commands ###
